/** @type {import('prettier').Config} */
module.exports = {
    endOfLine: "crlf",
    semi: false,
    singleQuote: false,
    tabWidth: 4,
    trailingComma: "es5",
    importOrder: [
        "^(react/(.*)$)|^(react$)",
        "^(next/(.*)$)|^(next$)",
        "<THIRD_PARTY_MODULES>",
        "",
        "^types$",
        "^@/src/types/(.*)$",
        "^@/src/config/(.*)$",
        "^@/src/lib/(.*)$",
        "^@/src/hooks/(.*)$",
        "^@/src/components/ui/(.*)$",
        "^@/src/components/(.*)$",
        "^@/src/registry/(.*)$",
        "^@/src/styles/(.*)$",
        "^@/src/app/(.*)$",
        "",
        "^[./]",
    ],
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
    plugins: ["@ianvs/prettier-plugin-sort-imports"],
}
